
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE LPAREN MINUS NUMBER PLUS PRINT QUOTE RPAREN TIMESexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : factorterm : PRINT termterm : QUOTE term QUOTEfactor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'PRINT':([0,4,5,7,8,9,],[4,4,4,4,4,4,]),'QUOTE':([0,3,4,5,6,7,8,9,12,13,17,18,19,20,],[5,-6,5,5,-9,5,5,5,-7,19,-4,-5,-8,-10,]),'NUMBER':([0,4,5,7,8,9,10,11,],[6,6,6,6,6,6,6,6,]),'LPAREN':([0,4,5,7,8,9,10,11,],[7,7,7,7,7,7,7,7,]),'$end':([1,2,3,6,12,15,16,17,18,19,20,],[0,-3,-6,-9,-7,-1,-2,-4,-5,-8,-10,]),'PLUS':([1,2,3,6,12,14,15,16,17,18,19,20,],[8,-3,-6,-9,-7,8,-1,-2,-4,-5,-8,-10,]),'MINUS':([1,2,3,6,12,14,15,16,17,18,19,20,],[9,-3,-6,-9,-7,9,-1,-2,-4,-5,-8,-10,]),'RPAREN':([2,3,6,12,14,15,16,17,18,19,20,],[-3,-6,-9,-7,20,-1,-2,-4,-5,-8,-10,]),'TIMES':([2,3,6,12,13,15,16,17,18,19,20,],[10,-6,-9,10,10,10,10,-4,-5,-8,-10,]),'DIVIDE':([2,3,6,12,13,15,16,17,18,19,20,],[11,-6,-9,11,11,11,11,-4,-5,-8,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,7,],[1,14,]),'term':([0,4,5,7,8,9,],[2,12,13,2,15,16,]),'factor':([0,4,5,7,8,9,10,11,],[3,3,3,3,3,3,17,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser.py',5),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','parser.py',9),
  ('expression -> term','expression',1,'p_expression_term','parser.py',13),
  ('term -> term TIMES factor','term',3,'p_term_times','parser.py',17),
  ('term -> term DIVIDE factor','term',3,'p_term_div','parser.py',21),
  ('term -> factor','term',1,'p_term_factor','parser.py',25),
  ('term -> PRINT term','term',2,'p_term_print','parser.py',29),
  ('term -> QUOTE term QUOTE','term',3,'p_term_string','parser.py',33),
  ('factor -> NUMBER','factor',1,'p_factor_num','parser.py',37),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser.py',41),
]
