
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE INPUT LPAREN MINUS NUMBER PLUS PRINT RPAREN TIMESexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : factorterm : PRINT termterm : INPUT termterm : LPAREN term RPARENfactor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'PRINT':([0,4,5,6,8,9,19,],[4,4,4,4,4,4,4,]),'INPUT':([0,4,5,6,8,9,19,],[5,5,5,5,5,5,5,]),'LPAREN':([0,4,5,6,8,9,10,11,19,],[6,6,6,6,6,6,19,19,6,]),'NUMBER':([0,4,5,6,8,9,10,11,19,],[7,7,7,7,7,7,7,7,7,]),'$end':([1,2,3,7,12,13,16,17,18,20,21,22,],[0,-3,-6,-10,-7,-8,-1,-2,-4,-5,-9,-11,]),'PLUS':([1,2,3,7,12,13,14,15,16,17,18,20,21,22,],[8,-3,-6,-10,-7,-8,-3,8,-1,-2,-4,-5,-9,-11,]),'MINUS':([1,2,3,7,12,13,14,15,16,17,18,20,21,22,],[9,-3,-6,-10,-7,-8,-3,9,-1,-2,-4,-5,-9,-11,]),'RPAREN':([2,3,7,12,13,14,15,16,17,18,20,21,22,],[-3,-6,-10,-7,-8,21,22,-1,-2,-4,-5,-9,-11,]),'TIMES':([2,3,7,12,13,14,16,17,18,20,21,22,],[10,-6,-10,10,10,10,10,10,-4,-5,-9,-11,]),'DIVIDE':([2,3,7,12,13,14,16,17,18,20,21,22,],[11,-6,-10,11,11,11,11,11,-4,-5,-9,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,6,19,],[1,15,15,]),'term':([0,4,5,6,8,9,19,],[2,12,13,14,16,17,2,]),'factor':([0,4,5,6,8,9,10,11,19,],[3,3,3,3,3,3,18,20,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser.py',5),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','parser.py',9),
  ('expression -> term','expression',1,'p_expression_term','parser.py',13),
  ('term -> term TIMES factor','term',3,'p_term_times','parser.py',17),
  ('term -> term DIVIDE factor','term',3,'p_term_div','parser.py',21),
  ('term -> factor','term',1,'p_term_factor','parser.py',25),
  ('term -> PRINT term','term',2,'p_term_print','parser.py',29),
  ('term -> INPUT term','term',2,'p_term_input','parser.py',33),
  ('term -> LPAREN term RPAREN','term',3,'p_term_paren','parser.py',37),
  ('factor -> NUMBER','factor',1,'p_factor_num','parser.py',40),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser.py',44),
]
